### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by roccomuso** [njh/marquette#9]
Is it possible to have a live demo or screenshot of the project added to the README?

thanks

**Comment by njh** [comment]
While the project does work it is semi-abandoned.

I am now using [homekit2mqtt](https://github.com/hobbyquaker/homekit2mqtt).

However I will try and get a screenshot and README uploaded.

**Comment by njh** [comment]
I have added a screenshot to the [README](https://github.com/njh/marquette/blob/master/README.md).
